version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - my-network

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/configdb
      - mongodata:/data/db
    networks:
      - my-network
  
  tdungeon:
    container_name: tdungeon
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - NODE_ENV=DOCKER_DEV
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - redis
    networks:
      - my-network

networks:
  my-network:
volumes:
  redisdata:
  mongodata: